#
# This is the validation schema of the configuration file for duplicity_backup_s3
#
# We use 'cerberus' to validate the dictionary
# src: https://docs.python-cerberus.org/en/stable/validation-rules.html

aws:
  type: dict
  allow_unknown: false
  schema:
    AWS_ACCESS_KEY_ID:
      type: string
    AWS_SECRET_ACCESS_KEY:
      type: string
gpg:
  type: dict
  allow_unknown: false
  schema:
    PASSPHRASE:
      type: string
    GPG_KEY:
      type: string

backuproot:
  required: true
  type: string

excludes:
  type: list
  schema:
    type: string

includes:
  type: list
  schema:
    type: string

remote:
  required: true
  type: dict
  allow_unknown: false
  schema:
    uri:
      required: false
      type: string
    bucket:
      required: false
      type: string
    path:
      required: false
      type: string
    endpoint:
      required: false
      type: string
    s3-european-buckets:
      type: boolean
    use-new-style:
      type: boolean

full_if_older_than:
  type: string

log-path:
  type: string

volsize:
  type: integer

extra_args:
  type: list
  required: false
  schema:
    type: string
